jwtKey: abcdefg
debug: true

# CREATE DATABASE kf CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
db:
  driver: mysql  # mysql / postgres / sqlite ...
  dsn: "root:124x8Xawdasdx1r140xs$@tcp(localhost:3306)/kf?charset=utf8mb4&parseTime=True&loc=PRC"

web:
  addr: 0.0.0.0
  port: 8081
  staticDir: ./static

redis:
  db: 0
  address: localhost:6379
  password: "238XSfh98xa"

billConfig:
  accounts:
    - username: admin
      password: admin


nsq:
  addrs:
    - 127.0.0.1:4150
  messageTopic: im_message
  messageTopicGroup: im_message_group

httpClient:
  logicAddress: http://127.0.0.1:3111
  timeout: 60
  proxy:


## 卡密套餐，按天划分
cardPackages:
  - id: "daily"
    price: 10
    day: 1

  - id: "weekly"
    price: 50
    day: 7

  - id: "monthly"
    price: 180
    day: 30