jwtKey: abcdefg
debug: true

# CREATE DATABASE kf CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
db:
  driver: mysql  # mysql / postgres / sqlite ...
  dsn: "root:124x8Xawdasdx1r140xs$@tcp(localhost:3306)/kf?charset=utf8mb4&parseTime=True&loc=PRC"

web:
  addr: 0.0.0.0
  port: 8081
  staticDir: ./data/static
  cdnHost: http://localhost:8081/static/upload
  uploadDir: ./data/static/upload
  kfManagerAddress: https://manager.smartkf.top

redis:
  db: 3
  address: localhost:6379
  password: "238XSfh98xa"

billConfig:
  accounts:
    - username: admin
      password: admin


nsq:
  addrs:
    - 127.0.0.1:4150
  messageTopic: im_message
  messageTopicGroup: im_message_group
  orderExpireTopic: order_expire_notify
  orderExpireGroup: order_expire_notify_group

httpClient:
  socketServerAddress: http://127.0.0.1:9000
  timeout: 60
  proxy:


## 卡密套餐，按天划分
cardPackages:
  - id: "daily"
    price: 10
    day: 1
    name: '日卡'

  - id: "weekly"
    price: 50
    day: 7
    name: '周卡'

  - id: "monthly"
    price: 180
    day: 30
    name: '月卡'

payment:
  host: http://localhost:8082
  token: 1234
  appId: kf
  fromMail: admin@smartkf.top

ip2region:
  xdbPath: ./ip2region.xdb
  registryApiKey: ira_AnrzYNqRz8M64Mj7VvqFylbrIj67Rh3yFi29
  proxy: http://127.0.0.1:10081
  timeout: 5

socketIo:
  host: 'localhost:9000'
  fullHost: 'ws://localhost:9000/'
