services:
  kf-api:
    image: kf-api:latest
    volumes:
      - ./prod/config.yaml:/app/config.yaml
    command:
      - /app/app
    ports:
      - "8081:8081"
    restart: always
    networks:
      - mysql_kf_network
      - kf_service_network

networks:
  mysql_kf_network:
    external: true
  kf_service_network:  # 组网，将goim2添加到这个组网，就可以实现内网通信.
    driver: bridge