services:
  kf-api:
    image: kf-api:latest
    volumes:
      - ./data/prod/config.yaml:/app/config.yaml
      - /www/cdn:/www/cdn
    command:
      - /app/app
    ports:
      - "8081:8081"
    restart: always
    networks:
      - kf_network

networks:
  kf_network:
    external: true
