name: Build macOS Application

on:
  push:
    tags:
      - 'v*'  # 仅在以 'v' 开头的标签时触发
env:
  APP_NAME: "kf-api"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        arch: [linux]  # amd64 for Intel, arm64 for M2

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.23.2'  # 设置 Go 版本

      - name: Build the application
        run: |
          go mod tidy
          make build

      - name: Create dist archive
        run: |
          tar -czvf app.tar.gz ./bin/app  

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: app.tar.gz

      - name: Send Curl Request
        run: |
          TAG_NAME=$(git describe --tags --abbrev=0)
          REPO_NAME="${{ github.repository }}" 
          curl -X POST -H "Content-Type: application/json" -d '{"repo": "'"${REPO_NAME}"'","tag": "'"${TAG_NAME}"'"}'  https://ci.smartkf.top/release